### ISSUE TITLE
Not able to use JMeter docker extension

### ISSUE THREAD

**Issue by vinda-parab** [QAInsights/jmeter-docker-extension#12]
Error creating container WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested please check Docker daemon logs.

Host Machine: 
Windows 11 Enterprise
64-bit operating system, x64-based processor

**Comment by vinda-parab** [comment]
@QAInsights Can you pls suggest on above mentioned observation?

**Comment by QAInsights** [comment]
@vinda-parab the image `qainsights/jmeter` supports only Linux. Not Windows. You can use [this image](https://hub.docker.com/repository/docker/qainsights/windows-docker-jmeter/general). But I have not tested the extension with Windows image.

**Comment by vinda-parab** [comment]
hi @QAInsights Thanks for looking into this.
Does it means the Host OS has to be only Linux?
On  Windows host machine with the Docker Desktop - switched to Linux Containers - this image will not work?

**Comment by QAInsights** [comment]
WSL should work, but I never tested. @vinda-parab

**Comment by QAInsights** [comment]
Closing this issue.

**Comment by vinda-parab** [comment]
@QAInsights 
_> WSL should work, but I never tested. @vinda-parab_

Tried WSL. https://hub.docker.com/r/qainsights/windows-docker-jmeter is throwing an error while pulling.

docker pull qainsights/windows-docker-jmeter
Using default tag: latest
latest: Pulling from qainsights/windows-docker-jmeter
4612f6d0b889: Retrying in 1 second
5ee7a7ea9cf2: Retrying in 1 second
31b2acce136e: Download complete
55ef2f84414a: Download complete
46a06d65ee30: Download complete
dc0c8f0ac1d4: Download complete
6daa15daa1dc: Download complete
dc63c2c4981f: Download complete
7925e6dd19b2: Download complete
4f55dcde2adf: Download complete
2f0afad8f65d: Download complete
44f840ad743f: Download complete
139e738ef91b: Download complete
4ec311bd75f0: Download complete
daa5e220db97: Download complete
176b15cfffa2: Download complete
32495da77964: Download complete
51fd9af43c40: Download complete
682d77672335: Download complete
**dial tcp: lookup mcr.microsoft.com: no such host**

**Comment by QAInsights** [comment]
You are mix and matching the image. For WSL, you are supposed to use `qainsights/jmeter`, not Windows image. @vinda-parab
