### ISSUE TITLE
Not able to use qainsights/jmeter-docker-extension in Windows Laptop

### ISSUE THREAD

**Issue by vishnuprakash9845** [QAInsights/jmeter-docker-extension#4]
Thank you for developing this Extension.

### Actual Steps I did as a user

1. Installed the Latest Desktop Docker 4.25.0 (126437)
2. Pulled the `docker pull qainsights/jmeter` image and installed the qainsights/jmeter-docker-extension. 
3. Developed the TestScript under TestPlan in Jmeter and Tested it.
4. Added the details in the qainsights/jmeter-docker-extension and clicked on Run Jmeter Test and got below error in the notification

_Error creating container WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested please check Docker daemon logs._

![image](https://github.com/QAInsights/jmeter-docker-extension/assets/24207575/efc60220-4fac-4519-b550-a3aeff4dc104)

**Later got to know post debugging, the image is for Linux platform.**

![image](https://github.com/QAInsights/jmeter-docker-extension/assets/24207575/6ab9dd26-f618-4800-b548-1810442c374b)

----------------------------------------------------------------------------------------------------------------------------------------------

Then again I tried to pull the windows image using below one, but unfortunately it couldn't pull it.

`docker pull qainsights/windows-docker-jmeter`

![image](https://github.com/QAInsights/jmeter-docker-extension/assets/24207575/10d7008d-aa32-427e-817b-f15ec45a57d7)

![image](https://github.com/QAInsights/jmeter-docker-extension/assets/24207575/1a7161e8-052f-44c0-a97b-a32fdf5a0634)

Here are my System Details:
OS: Microsoft Windows 10 Enterprise
Version: 10.0.19.45

I wanted to check and explore qainsights/jmeter-docker-extension in Windows Laptop. If you have a moment, could you kindly share any insights or suggestions on resolving this matter? Your expertise would be immensely valuable.

**Comment by QAInsights** [comment]
@vishnuprakash9845 The Apache JMeter Docker Extension works only on Linux/Mac OS. It will not work in Windows yet. I have no plans to make it compatible with Windows for now; as 99% of containers will run on *nix OSes. 

For `qainsights/windows-docker-jmeter` - it will work for AMD arch. If your arch is different, you can build it by referring to my repo.
